### ISSUE TITLE
Having trouble running Scyland3D when installed from pip

### ISSUE THREAD

**Issue by patrikhuber** [ybayle/Scyland3D#10]
Hi!

If I clone the repo from git and go into the `Scyland3D\Scyland3D` directory on a command-line, I can successfully run the example and it creates the `.csv` file. However, when I create a new virtualenv and do `pip install Scyland3D`, then I can still `import` the module without error, but it doesn't seem to have any functions. `help(Scyland3D)` then looks like an empty module and trying to call any function fails, e.g. `AttributeError: module 'Scyland3D' has no attribute 'pts2csv'`.

I tried this on both Windows and on WSL Ubuntu 18.04.

Anything that I might be doing wrong here?

**Comment by Kevin-Mattheus-Moerman** [comment]
@ybayle :wave: any updates on handling this issue?

**Comment by ybayle** [comment]
Thank for raising this issue. I have updated the Readme to indicate that it is necessary to use `from Scyland3D import Scyland3D` in order to avoid this kind of problem. Could you confirm that this solve the issue?

**Comment by patrikhuber** [comment]
I can confirm that using `from Scyland3D import Scyland3D` fixes this issue.

I don't know too much about packaging Python modules, but this seems a bit unusual to me. Though I've seen this syntax before of course, I would expect that a simple `import Scyland3D` should work too? Or subsequently, `import Scyland3D as S` should work too (but it doesn't). For example it's common practice to do `import tensorflow as tf` so I would expect that `import Scyland3D as S` needs to work as well?

**Comment by patrikhuber** [comment]
Your own tests also still fails since it uses `import Scyland3D`: https://github.com/ybayle/Scyland3D/blob/c75e13cb0f372a9a5a271931fbc0624d942435b9/test.sh#L2

Instead of just "fixing" this to `from Scyland3D import Scyland3D` it would be really good to know why the usual method doesn't work when it does work for lots of other libraries (and when Scyland3D is used from GitHub).

**Comment by ybayle** [comment]
> I can confirm that using from Scyland3D import Scyland3D fixes this issue.

:+1:

> I don't know too much about packaging Python modules, but this seems a bit unusual to me. Though I've seen this syntax before of course, I would expect that a simple import Scyland3D should work too? Or subsequently, import Scyland3D as S should work too (but it doesn't). For example it's common practice to do import tensorflow as tf so I would expect that import Scyland3D as S needs to work as well?

The keyword `as` serves a different purpose: it is just an alias. It actually works fine if you write:
```
from Scyland3D import Scyland3D as S
S.pts2csv()
```

Moreover here, `Scyland3D` is the name of the package and the name of the module. That's why you need to use `from Scyland3D import Scyland3D`, which is common practice for this kind of small packages. For tensorflow there are multiple layers of package/module/functionalities so that's why you encounter import such as `from tensorflow.python.keras.layers import Input, Dense`.

> Your own tests also still fails since it uses import Scyland3D: 

On my machine, the test works because the test.sh script considers the Scyland3D module directly as it is stored in the same folder.
If the test fails on your machine could you describe more precisely the error you encounter?

**Comment by patrikhuber** [comment]
> Moreover here, Scyland3D is the name of the package and the name of the module. That's why you need to use from Scyland3D import Scyland3D, which is common practice for this kind of small packages.

I see! As I said I am not too familiar with Python packaging, so I wasn't aware of the package/module difference. But that makes sense.

>> If the test fails on your machine could you describe more precisely the error you encounter?

I think it only failed because I tried to run the test manually, using the Scyland3D module from `pip`, and not using the one from the directory (where the test script is located). So I think it's all good.

I think it's all fine here, so I'm going to close the issue.
